### ISSUE TITLE
Event Recorder with RTOS2 - how to use

### ISSUE THREAD

**Issue by FerdinandEn** [ARM-software/CMSIS_5#113]
How can I use Event Recorder with RTOS2?

I have changed the setting  to Source.

**Comment by ReinhardKeil** [comment]
The team is currently adding the stubs for the Event Recorder to RTOS2.  This should be finished in about 2 weeks.

**Comment by RobertRostohar** [comment]
Support for Event Recorder has been added to RTX5.

**Comment by ReinhardKeil** [comment]
This is no part of CMSIS 5.0.1. Therefore closing this issue.

**Comment by rizickus** [comment]
I bet it is not the right place to ask, but...
Is there any way how to save Event Recorder information to file using command line or debug script, instead of clicking on IDE? We would like to automate some parts of our debug routines. Event Recorder is really helpful tool and ability to automatically collect events directly to csv file would be very useful.

**Comment by JonatanAntoni** [comment]
Hi @rizickus.
The Event Recorder integration into MDK/uVision is not part of CMSIS.
The tools team always has command line support on the backlog. Please consider to file a customer service request at [silver.arm.com](http://www2.keil.com/support/silver) if you have any tool issue.
