### ISSUE TITLE
CMSIS-DSP: loop unroll

### ISSUE THREAD

**Issue by escherstair** [ARM-software/CMSIS_5#1240]
[Python script](https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/DSP/cmsisdspconfig.py) to configure CMSIS-DSP library has on option named "LOOPUNROLL".
It's set to True by default, and this adds `-DARM_MATH_LOOPUNROLL` to the command line build.
As far as I can see [here](https://www.keil.com/pack/doc/CMSIS/DSP/html/index.html)

- ARM_MATH_LOOPUNROLL:
  Define macro ARM_MATH_LOOPUNROLL to enable manual loop unrolling in DSP functions

Since it has a True default in the Python script, I could think that it should be enabled in common situations.
But I can be wrong.

Where can I find detailed info on "LOOPUNROLLING"?
When should I enable/disable it?
Does it depend on the device?

Thanks in advance

**Comment by happyTonakai** [comment]
https://developer.arm.com/documentation/dui0472/c/compiler-coding-practices/loop-unrolling-in-c-code this should help

**Comment by escherstair** [comment]
Thank you.
This is quite clear.

**Comment by christophe0606** [comment]
@escherstair Sorry for late answer.
It is highly compiler dependent. In theory, this CMSIS-DSP option should no more be needed because compilers are getting very good at unrolling loops.

In practice, and mainly with fixed point functions, we observe that this option is still useful and the manually unrolled versions have better performances.

But you have to benchmark to be sure.
