### ISSUE TITLE
arm_nn_doubling_high_mult_no_sat in CMSIS NN

### ISSUE THREAD

**Issue by MAMOMIMOMU** [ARM-software/CMSIS_5#1361]
Hi, I have a question on this rounding mul function. As long as I can see, function returns multiplicand times multiplier rounded at b_30. Since b_30 is added by 1, if this bit of the result of the multiplication is 1, it's carry up. If b_30 is 0, it's carry down. Then this number is shifted to the right, and cast to be int32. This means b_62 to b_31 of the previous number will be the return value. However, if b_63 is 1(which means this number is minus) and b_62 is 0, after the shift operation, this number will become plus because b_62 moves to b31 which is MSB in int32. Is it what you expect? Also why don't you add 1 to b_31 for rounding instead of b_30, and shift the number by 32 to the right? If you do this, sign will also be ok.

**Comment by mansnils** [comment]
Hi @MAMOMIMOMU 
You are correct that arm_nn_doubling_high_mult_no_sat does not handle the case you describe. Yes it is expected since b_63 should not be 1 for the given input or at least intended input. It is intended for requantization where the scale (i.e. multiplier or m2) is a positive integer. For the case you describe arm_nn_doubling_high_mult could be used instead. Hope that helps.
