### ISSUE TITLE
CMSIS I2C for beginner

### ISSUE THREAD

**Issue by onurdemirel** [ARM-software/CMSIS_5#375]
Hello, 

I am a new engineer and working with CMSIS on my TWR-KE18F board. I am trying to communicate via I2C with my onboard accelerometer. My first goal is obtaining the value from WhoAmI register.

My piece of code is here:

EXAMPLE_I2C_MASTER.Initialize(lpi2c_master_callback);
EXAMPLE_I2C_MASTER.PowerControl(ARM_POWER_FULL);
EXAMPLE_I2C_MASTER.Control(ARM_I2C_BUS_SPEED,ARM_I2C_BUS_SPEED_STANDARD);

g_master_txBuff[0] = 0x0D;      //WhoAmI register = 0x0D
EXAMPLE_I2C_MASTER.MasterTransmit(SLAVE_ADR,g_master_txBuff,1,true);

while(!ARM_I2C_EVENT_TRANSFER_DONE)
{}
while(EXAMPLE_I2C_MASTER.GetStatus().busy)
{}

EXAMPLE_I2C_MASTER.MasterReceive(SLAVE_ADR,g_master_rxBuff,1,false);

PRINTF("0x%2x", g_master_rxBuff[0]);

I obtain 0x00.

I will apreciate any help or anything for me to read. 

Onur

**Comment by JonatanAntoni** [comment]
Hi @onurdemirel,

Did you carefully follow the examples given in the [documentation](https://www.keil.com/pack/doc/CMSIS/Driver/html/group__i2c__interface__gr.html)?

Did you try to run the example project shipped with the [board support pack](https://www.keil.com/boards2/nxp/twr_ke18f/) for your device?

Cheers,
Jonatan

**Comment by onurdemirel** [comment]
Hi @JonatanAntoni 

Thanks for quick reply. 

I kind of rearrange the example of I2C communication of two different boards which is given in the board support back. As far as I understand, the example is only sending data to other board and reading what that sends back. That is not reading a data from a certain register from the slave device. I tried to read data from slave's register. 
While doing it I follow the CMSIS documentation that you linked and I2C protocol documentations. 

Thanks,
Onur

**Comment by JonatanAntoni** [comment]
Hi @onurdemirel,

The demos are very generic and hence not specific for your slave device. But they should clearly show how to issue read and write transactions between master and slave. Addressing the correct register of your slave device and reading back its content should only be a matter of sending the correct data sequence.

Please be aware that CMSIS only specifies the driver API. The concrete driver implementation is subject of the device family or board support pack vendor. You might want to:
- Attach an I2C analyzer (digital probe) to your board in order to verify the actually transmitted data.
- Get in touch with the driver vendor (I guess NXP) for more details about the peripheral functionality.

If you have further questions regarding the API specification or have any suggestions to enhance the documentation your feedback and contribution is always appreciated.

Cheers,
Jonatan

**Comment by onurdemirel** [comment]
Hi @JonatanAntoni ,

You are right I only try to inspire from demo codes and understand the way of thinking.

 I overcome the problem that I asked. The problem was I didn't wait for completion flag and see that I have to wait for it. After the completion flag is set, the read operation gives the content of the register. 

I am now working on writing some data and reading some data from accelerometer. I have still problems timebeing but I am working on them. If I feel desperate again I will ask it.

Thanks,
Onur

**Comment by JonatanAntoni** [comment]
Thank you for letting us know that its basically working for you, now. Please close this issue if your questions are answered. Feel free to raise additional requests at any time.
