### ISSUE TITLE
data format for weights

### ISSUE THREAD

**Issue by uu-kameshm** [ARM-software/CMSIS_5#379]
Hi

I have below queries related to the expected data format for the weights (to layers such as convolution etc,)

- It seems that the CMSIS NN function APIs does not support Single precision Floating point data type.
What would happen if we provide the weights in single precision FP data type - does the CMSIS NN API expected to convert the weights to the data format required for them internally?

- If not, Is there any API to convert from Single precision FP data format to the data format required for the APIs to work 

- If the user is expected to convert from Single precision FP format to the format needed for the CMSIS NN APIs , what is/are the data formats expected. Is there any quantization format specifically needed for the APIs to work.

It would help, if you could clarify on the above.

Thanks
Kamesh

**Comment by kwagyeman** [comment]
Hi, checkout the OpenMV Cam implementation:

https://github.com/openmv/openmv/tree/master/ml/cmsisnn

**Comment by liangzhen-lai** [comment]
Hi @uu-kameshm ,

Here are the answers:
1. CMSIS-NN supports 16-bit and 8-bit integer type (i.e., q15_t and q7_t). The models have to be quantized first in order to use these functions.
2. There will be tools available for model deployment. Before that becomes available, we have also released some example [scripts](https://github.com/ARM-software/ML-examples/tree/master/cmsisnn-cifar10) which translate trained CNN model in Caffe into the API calls. We also have some [documentation](https://github.com/ARM-software/ML-KWS-for-MCU/blob/master/Deployment/Quant_guide.md) explaining the quantization steps.

Let me know if this answers your question.

Thanks,
Liangzhen

**Comment by uu-kameshm** [comment]
Hi @kwagyeman 

Thanks for the reply. I am looking for availability of tools/APIs in CMSIS to quantize trained models to 16-bit/8-bit integer type for a Non-Caffe model (without need to convert the model to Caffe format).

@liangzhen-lai
When is it expected to have the tools/APIs to quantize trained models for other frameworks/user defined models (models that are not in Caffe format). 

Thanks
Kamesh

**Comment by majianjia** [comment]
> 
> 
> Hi @kwagyeman
> 
> Thanks for the reply. I am looking for availability of tools/APIs in CMSIS to quantize trained models to 16-bit/8-bit integer type for a Non-Caffe model (without need to convert the model to Caffe format).
> 
> @liangzhen-lai
> When is it expected to have the tools/APIs to quantize trained models for other frameworks/user defined models (models that are not in Caffe format).
> 
> Thanks
> Kamesh

Not until now. No one wants to run the Caffe examples again and again but it is the only doc they have. 
The documents are not easy to understand. I am using Tensorflow and there is none. The important parts are just missing. The CMSIS-NN lib has very little info about how to input a data.

**Comment by felix-johnny** [comment]
@uu-kameshm Some late tidying up of tickets. The tools that you ask for will unfortunately not be available in CMSIS-NN as only support for TFLu API's are done now. Info about it can be found in https://github.com/ARM-software/CMSIS_5/tree/develop/CMSIS/NN#legacy-vs-tfl-micro-compliant-apis.
