### ISSUE TITLE
__LDA(EX)/__STL(EX) don't constrain compiler reordering

### ISSUE THREAD

**Issue by kjbracey-arm** [ARM-software/CMSIS_5#494]
CMSIS has `__LDA`/`__STL` and `__LDAEX`/`__STLEX` family of functions, but the toolchains are inconsistent about what compiler barriers are present. Some functions use `volatile asm` with no compiler barriers, some use `volatile asm` with a memory clobber (ie a barrier), others use compiler built-ins, which will have compiler acquire/release semantics.

As some definitions lack any barrier, safe use of these macros requires code like:

    __LDAEX/STLEX for atomic_flag_test_and_set
    __compiler_barrier to stop following code moving ahead of __LDAEX
    do work protected by flag
    __compiler_barrier to stop preceding code moving after __STL
    __STL for atomic_flag_clear

But that's excessively pessimistic if the functions are using built-ins - adding the barriers loses some of the benefit of the builtins - having less-restrictive ordering than a complete fence.

It would be better if the assembler forms met the minimum expected acquire/release compiler semantics - I believe that can only be done as a full fence via a "memory" clobber. But having that full fence as a clobber only in the assembler versions, rather than all the time for every platform in the user's code is preferable.

Then user code can safely be:

    __LDAEX/STLEX for atomic_flag_test_and_set
    do work protected by flag
    __STL

I note that more functions could be using built-ins, avoiding the need for a memory clobber - `__LDA` and `__STL` could be implemented using `__c11_atomic_load` (clang) or `__atomic_load_4` (gcc).  (Assuming they map - do they always if ARMv8, or is there a "SMP" compiler flag that activates CPU-ordering instructions inside atomics?)

**Comment by kjbracey-arm** [comment]
Came up with this while concocting an example of where why we might need an explicit Mbed OS compiler barrier for https://github.com/ARMmbed/mbed-os/pull/9247 - that we'd need barriers around `__STLB` inside `atomic_flag_clear`.

**Comment by ReinhardKeil** [comment]
These functions http://arm-software.github.io/CMSIS_5/Core/html/group__intrinsic__CPU__gr.html only generate the related CPU instruction and should not add further barrier instructions (there are separate instructions for that).

Usually a compiler should know that LDEX, STEX are special instructions and should not move code around that could cause side effects.  What compiler are you using and what is the specific code example that caused the issue.  I would consider to raise a question to the compiler team instead.

**Comment by kjbracey-arm** [comment]
I'm talking about compiler barriers here to constrain compiler reordering, not extra instructions.

If using built-ins, certainly the compiler should know not to reorder. But when putting in your own assembler fragments, there's nothing stopping the compiler from reordering

       *state = foo;
       __STL(&lock, 0); // release lock on state

if __STL is just `__ASM volatile ("stl %1, %0" : "=Q" (*ptr) : "r" ((uint32_t)value) );`

That can be resolved by adding a "memory" clobber to the assembler, making it a full fence - I don't believe there's any finer-grained way of doing it, other than going to a built-in, such as an `__atomic`.

Note that this ordering constraint is purely needed because of the "acquire" or "release" semantics of the instruction, not the "exclusive". So `__STL` and `__STLEX` need a compiler ordering constraint at least matching their hardware "sequentially-consistent release". `__STREX` doesn't need ordering - it could be part of a "relaxed" increment.

**Comment by ReinhardKeil** [comment]
@kjbracey-arm thanks for all the explanations.  I now understand your concerns.  Basically you would like to add a "compiler barrier" that ensures that no code re-ordering happens.

**Comment by kjbracey-arm** [comment]
Another note on this particular case - the `__STL` and `__LDA` do need an ordering barrier, but they don't really need to be `asm volatile`.

Scanning the codebase, I can see a bunch of other unnecessary `asm volatile`s - I'll raise a separate issue.

**Comment by GorgonMeducer** [comment]
There are two levels of questions twisting here. 

1. Whether compiler will schedule the instruction orders or not when either build-in intrinsics is used or inline assembly code is used. 
- When using buid-in, since compiler has the visibility, it will not change the order around those build-ins. If not, it should be a defect of compiler. Report it.
- When using inline assembly code, since compiler has no visibility for those critical instructions, i.e. STL, LDA and etc, there is no guarantee that the compiler will not change the order. So the "compiler scheduling barrier" is required for these scenarios.
**- CONCLUSION: To solve this question, we need an "compiler scheduling barrier" which ensures the order of some critical local logic.** 


Assume when build-in and/or inline assembly code is used, compiler will not change the order of instructions around it, we come to next level of question, i.e.

Do we need "asm volatile" for __STL, __LDA and corresponding EX versions.

My answer is, depends on the programmers' understanding and style of coding. 
For example, I am a newbie, I just want to the effect of "One-Way" barriers, i.e. LDA and STL, but I don't really need it to access any variables. What should I do, I simply write some dummy access using LDA and STL. I know it is stupid, but it works as I expected (remember, I only want it to work as "one-way" barrier, I don't want to bother myself about how to use the LOAD/STORE functionality).

So, to only use the "one-way barrier" function, I want to use "asm volatile" to prevent it from being optimised away.

- Hey, You cannot call me stupid!! I do what I want, I want the "one-way-barrier", but you don't provide a dedicated instruction for "one-way-barrier" only. You give me this LDA and STL. OK. OK. I use it. But don't judge me why I don't use it "wisely"

That's just an example. 
If you think we should always tell others what's right or wrong. We can remove "asm volatile" from __STL and __LDA. And don't forget, sometimes we might do something right based on our own environment, but there are some more "correct" way to use it.

**Comment by kjbracey-arm** [comment]
I agree with your analysis of the scheduling.

On volatile, as I discuss here for another intrinsic, https://github.com/ARM-software/CMSIS_5/pull/502, the `volatile` is required anyway because the function prototype has `volatile` on its pointer. So removing it is a non-starter.

But you're right that because STL and LDA have the ordering semantics on the CPU, we couldn't just not output them. They have to be there in the instruction stream, or at least an equivalent barrier. We could drop the load if the pointer wasn't non-volatile, but we couldn't drop the CPU barrier.
