### ISSUE TITLE
all DSP floating point operations should support double precision (float64_t) operands

### ISSUE THREAD

**Issue by bigbrett** [ARM-software/CMSIS_5#584]
It seems a bit silly that ARM advertises that fpv5 has double precision FPUs, but there is extremely limited support for float64_t in the ARM DSP library. If we get a chip with a double precision floating point unit, we probably want to use it. 

For example, all the matrix operation functions have f32 variants, but the only thing it appears you can do to an f64 matrix is invert it (unless I'm missing something in the source code....can't find any other f64 functions except `arm_mat_inverse_f64`). 

Is there any way we could f64's treated as first class citizens in the DSP library?

**Comment by christophe0606** [comment]
@bigbrett f64 support is definitely in our plans but I cannot share any timeline.

**Comment by udoe** [comment]
I do need support for float64_t as well, specifically for the FIR Interpolator filter.

**Comment by JBecka** [comment]
Hello, 
our project is based on an ARM Cortex-M7 SoC with DP FPU.
We would like to perform FFT on 2048 points using double precision (f64).
At the moment the support of double precision floating point format in the CMSIS-DSP library seems to be very limited.
This core has been there for some time already, when we selected this device for our next project, we didn't expect that support of double precision may be missing in CMSIS-DSP.
Considering the number of similar comments appearing here, 
could you please treat this request with priority?
Thank you.

**Comment by christophe0606** [comment]
There are no specific intrinsics for float64. So converting a function from float32 to float64 is basically just replacing the types. Then the compiler will manage the details.

As a consequence, since there are many other things to solve and improve in the CMSIS-DSP, we won't focus on this.

But pull requests with new functions are welcome :-)

If there is really a specific need and an unanticipated difficulty, then we will consider it on a case per case basis.

**Comment by bowen-hong** [comment]
Genius! You are genius, bro. :)
