### ISSUE TITLE
arm_rms_q15 always returns 0 on cortex m4 (stm32F373)

### ISSUE THREAD

**Issue by VasylYosypenko** [ARM-software/CMSIS_5#604]
Hello,

arm_rms_q15 always returns 0 on cortex m4 (stm32F373), lib Revision: V.1.4.5  

  code for reproducing:
```
  q15_t inTestArr[4] = {20, 20, 20, 20};
  q15_t res = 0;

  arm_rms_q15(inTestArr, 4u, &res);
```

The issue is 0 result during converting 
`__SSAT((sum / (q63_t)blockSize) >> 15`, 

and  API function 

`arm_sqrt_q15 `

takes zero as parameter.

Maybe is it expected for such small array, but I've not found information about minimum array requirements. 

Thanks,
Vasyl

**Comment by christophe0606** [comment]
It is "normal". There is a loss of accuracy when computing the square root since the shift required to convert to q15 is erasing least significant bits.

It is the same as issue https://github.com/ARM-software/CMSIS_5/issues/474

This function is focusing on avoiding saturation and this tradeoff implies less accuracy.

If you want to keep the accuracy in this case you need to rescale the values before applying the function and then on the result of the function.
