### ISSUE TITLE
size of the image exceeds the maximum

### ISSUE THREAD

**Issue by Shobica12** [ARM-software/CMSIS_5#660]
error: L6047U: The size of this image (47216 bytes) exceeds the maximum allowed for this version of the linker

how to rectify this error??

**Comment by jkrech** [comment]
This error is not caused by the CMSIS software but the tool-chain you are using to build your project.
From the error message I believe you are using the MDK-Lite edition of Arm Keil MDK which has a code size limit that you are exceeding (see KB article) http://www.keil.com/support/docs/3755.htm
Such questions do not belong here but should be raised here: https://developer.arm.com/support
