### ISSUE TITLE
arm_var_f32.c : Variance computation does not use common algorithm

### ISSUE THREAD

**Issue by etiennedemontalivet** [ARM-software/CMSIS_5#697]
File Path:  CMSIS_5/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.c 

I have just tested the ouptut of _arm_var_f32_. As detailed in the doc, it uses the algorithm :
`Result = sum(element - meanOfElements)^2) / numElement - 1`
Should'nt it be instead :
`Result = sum(element - meanOfElements)^2) / numElement` 
Same for the standard deviation ?

**Comment by etiennedemontalivet** [comment]
I would propose to compute variance and standard deviation always using `numElement` instead of `numElement - 1`
Attached are associated patches for variance and standard deviation, only for f32 format.

[arm_std_f32_patch.txt](https://github.com/ARM-software/CMSIS_5/files/3712219/arm_std_f32_patch.txt)
[arm_var_f32_patch.txt](https://github.com/ARM-software/CMSIS_5/files/3712220/arm_var_f32_patch.txt)

**Comment by christophe0606** [comment]
@etiennedemontalivet We have plan to rework those functions because they are not using the best algorithms in term of numerical stability.

The numElement - 1 is normal otherwise the estimator of the variance is biased.

You can look at the "Two-pass algorithm" here https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance 

Now the bias is not the only important factor for an estimator. So, this function may not match all the needs.

**Comment by etiennedemontalivet** [comment]
Thanks for pointing that out.
