### ISSUE TITLE
Add optimized filtering functions for half-band filters

### ISSUE THREAD

**Issue by escherstair** [ARM-software/CMSIS_5#803]
Half-band filters are a special category of filters used for factor-of-2 decimation.
Half-band filtering can be quite easily optimized because of the particular "shape" of the filter
_If's a FIR filter. There is an odd number of coefficients. There are 3 non-zero coefficients at the temporal center. Thereafter, in both directions, the coefficients alternate with zero values and non-zero values._
For this reason, only half of the multiplication are necessary (more or less).

I suggest to add optimized half-band filtering functions that skip the multiplication of coefficient equal to 0.

**Comment by christophe0606** [comment]
There is arm_fir_decimate_(f32|q31|q15). It is more general than half-band filter.
What performance improvement you would expect compared to arm_fir_decimate_(f32|q31|q15) ?

**Comment by escherstair** [comment]
More or less the double, since half of the coefficients (in known positions) are 0 by design, and so the multiplication can be skipped.
As an exampple, this is a set of ceofficients
  -0.0001220703125
    0
    0.00726318359375
    0
    -0.052398681640625
    0
    0.295196533203125
    0.49993896484375
    0.295196533203125
    0
    -0.052398681640625
    0
    0.00726318359375
    0
    -0.0001220703125

We can think of incrementing the counter by 2 (and so multuplying only the indexes [0], [2], [4], ....) and the multiplying the center coefficient.

**Comment by christophe0606** [comment]
So it is an additional optimization compared to what is already done in arm_fir_decimate ? (which by doing fir and decimate in same function is avoiding some useless computation).

**Comment by escherstair** [comment]
I cannot be 100% sure, but I think so.
When you use a decimation filter (decimation by a factor of `N`), only 1 sample every `N` is keeped in the output buffer (i.e. after the decimation) and so the calculation of the other `N-1` samples can be skipped.
This is true for every decimation FIR filter and I suppose these are the "useless computation" you mention in your message.

When you use a half-band decimation FIR filter (with `M` coefficients) and you calculate the sample (skipping the unnecessary `N-1` samples) you can save some other computation, since you know that `(M-1)/2` samples are equal to 0.

**Comment by llefaucheur** [comment]
Yes, rate conversion x2 and x3 can be optimized with SINCX filter shapes, and this needs to be specific subroutines. For half-band filters we can save some memory read by using the symmetry of the coefficients. The problem with SINCX shapes is it only attenuates 12dB at Fs/2, which results in having frequency images after oversampling, or distortions after decimation due to folding effects.
Reducing the bandwidth you can design your filter like this :
bw = 2.5; time = [-16:1:16]; b1 = (1/bw)*sinc (time/bw);
w = window(@hamming,1+2*16); b1 = b1 .* w'; b1 = b1 / sum(b1);
Which gives you 45dB attenuation at Fs/2, but you loose the symmetry and the zeroes.
The current solution is generic and allows using low-latency filters (non-linear phase filters).

**Comment by escherstair** [comment]
@llefaucheur I don't understand your comment.
With different methods you can design a halfband filter with desired passband ripple, stopband attenuation and transition width.
I'm able to get 80dB attenuation at Fs/2

**Comment by llefaucheur** [comment]
@escherstair and your filter has interleaved null coefficients ?

**Comment by polyclash** [comment]
Any snippet of code implementation?

**Comment by llefaucheur** [comment]
Hi, our approach is to deliver the generic solution, in open-source, and the community can tune it to specific needs. For example some people will be interested by CSD coefficients when their Cortex-M0 has no multiplier, others will normalize the central coefficient to 1 (instead of 0.499938964 above) to save more cycles, some will be interested by a small number of bits per coefficients, etc .. 
A paper of interest for SINC(x) is "Nine Digital Filters for Decimation and interpolation" (IEEE TRANSACTIONS ON ACOUSTICS, SPEECH, AND SIGNAL PROCESSING, VOL. ASSP-29, NO. 2, APRIL 1977). The last 7 unnormalized SINC are : 
[-1 0 9 16 9 0 -1]   [-3 0 19 32 19 0 -3]    [3 0 -25 0 150 256 150 0 -25 0 3]   [9 0 -44 0 208 346 208 0 -44 0 9]    [7 0 -53 0 302 512 302 0 -53 0 7]    [-6 0 33 0 -116 0 490 802 490 0 -116033 0 -6]    [18 0 -116 0 429 0 -1277 0 5042 8192 5042 0 -1277 0 429 0 -116 0 18]
