### ISSUE TITLE
Example test projects incorrect link paths

### ISSUE THREAD

**Issue by GI101** [ARM-software/CMSIS_5#919]
The example DSP test projects linked resource file paths are from an earlier CMSIS revision.
Such as project DspLibTest_FVP_A5 had different file names and or folder name too.

**Comment by christophe0606** [comment]
The DspLibTest is deprecated. We are developing new tests based on patterns generated by matlab or scipy as reference (instead of having a C reference code).

That's why this project has not been updated.

But the Examples folder should work.

The new test framework is in Testing. Since it is a work in progress it is still not fully documented.
(There is just a long README).

**Comment by GI101** [comment]
Thanks for the update!
