### ISSUE TITLE
RTOS2 uVision crash using osThreadAttr_t

### ISSUE THREAD

**Issue by FerdinandEn** [ARM-software/CMSIS_5#94]
Using osThreadNew() with osThreadAttr_t let uVision crash.

I have attached the example design.
[03-ThreadDefine.zip](https://github.com/ARM-software/CMSIS_5/files/544427/03-ThreadDefine.zip)

**Comment by RobertRostohar** [comment]
Could you provide a bit more information how to provoke the crash and which uVision version you have ?

I was able to duplicate one crash by using the provided example following these steps:
- build target
- start debug session
- run target and stop
- open View - Watch Windows - RTX RTOS

The crash occurred with uVision 5.21.1.0. It does not occur with newer uVision version so that particular problem has already been resolved.

**Comment by FerdinandEn** [comment]
I am using uVision V5.21.1.0 (MDK 5.21a)

uVision crash in Debugger after starting the MC-program, if RTX Component Viewer is open.

**Comment by RobertRostohar** [comment]
Thanks for the additional info.

The problem should be resolved in the latest uVision (will be part of the next MDK release).

**Comment by ReinhardKeil** [comment]
MDK 5.22 is fixing this problem.

**Comment by ReinhardKeil** [comment]
closing this issue now as there is no further activity
